version: '3.8'

services:
  # --- CONTENEDOR 0: LA BASE DE DATOS (MYSQL) ---
  base-datos:
    image: mysql:8.0
    container_name: container-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mi_base_datos  # <--- Cambia esto por el nombre real de tu BD
      MYSQL_USER: usuario_api
      MYSQL_PASSWORD: userpassword
    volumes:
      - datos-mysql:/var/lib/mysql
    networks:
      - red-proyecto

  # --- CONTENEDOR 1: BACKEND DESPACHOS ----
  api-despachos:
    container_name: container-despachos
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - base-datos  # Espera a que la BD levante
    networks:
      - red-proyecto

  # --- CONTENEDOR 2: BACKEND VENTAS ---
  api-ventas:
    container_name: container-ventas
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - base-datos  # Espera a que la BD levante
    networks:
      - red-proyecto

  # --- CONTENEDOR 3: FRONTEND ---
  frontend-app:
    container_name: container-front
    build:
      context: ./front_despacho
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api-despachos
      - api-ventas
    networks:
      - red-proyecto

# --- VOLÚMENES PARA NO PERDER LOS DATOS ---
volumes:
  datos-mysql:

# --- RED INTERNA DE DOCKER ---
networks:
  red-proyecto:
    driver: bridge